### ISSUE TITLE
TypeAccessor.Create performance

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [mgravell/fast-member#30]
Hello,

Is TypeAccessor.Create expensive to create? Is there anything to gain by caching the accessors?

Ideally, some guidance in the README.md should be provided ensuring us whether this is the case, as Reflection in general is quite slow.

Regards,
Björn Ali

**Comment by danielcrenna** [comment]
TypeAccessor.Create is already cached internally by way of using a Hashtable underneath. In other words, no, caching it twice won't provide more value.
