### ISSUE TITLE
No intellisense comments

### ISSUE THREAD

**Issue by digitalcoyote** [mgravell/fast-member#40]
I feel a lot of trial and error could be avoided by adding some xml comments to types and methods. 

I'd be willing to add these myself if there are no objections?

**Comment by mgravell** [comment]
sure, be my guest

**Comment by digitalcoyote** [comment]
I spoke too soon, they are there but not showing when using the NuGet package. There is a commit made sometime after the last upload to NuGet that has a comment stating it fixed the XML documentation target file. I'll assume this is something that is fixed but just not present on NuGet.

**Comment by mgravell** [comment]
I will see about re-packaging it
