### ISSUE TITLE
Is the TypeAccessor type thread-safe?

### ISSUE THREAD

**Issue by mukunku** [mgravell/fast-member#45]
Hello,

My question is simple really; I'm wondering whether I should statically cache my TypeAccessor's or not. 

Thanks.

**Comment by felixcollins** [comment]
Looking at the code it seems that the  TypeAccessor is already lazy created and cached in the library. However.. one would need to follow the IL generation to understand if it is thread safe. I'd like to know this too. Marc?

**Comment by Salgat** [comment]
Unfortunately it's technically not thread-safe, since it uses double-checked locking to determine whether a type is initialized (specifically [here](https://github.com/mgravell/fast-member/blob/master/FastMember/TypeAccessor.cs#L55)).

**Comment by mgravell** [comment]
That doesn't mean it isn't thread-safe.

**Comment by Salgat** [comment]
In this case instruction re-ordering inside the lock could allow for "lookup[type] = obj;" to occur before obj is finished constructing, allowing a second thread reading lookup[type] to be accessing an uninitialized, but not null, object.
