### ISSUE TITLE
CanWrite in Nuget v1.1.0

### ISSUE THREAD

**Issue by pimbrouwers** [mgravell/fast-member#48]
Maybe a silly question...

But why isn't Member.CanWrite exposed in the 1.1.0 NuGet package? Are we just behind?

**Comment by pimbrouwers** [comment]
Doing a bump here as I'm really needing this.

**Comment by mgravell** [comment]
I deployed 1.2.0 today; if it exists, it should be there

**Comment by pimbrouwers** [comment]
Thanks Marc. You DA BOMB.
