### ISSUE TITLE
Can't install 1.3.0 NuGet package on a 4.5 version .NET project

### ISSUE THREAD

**Issue by lei12** [mgravell/fast-member#51]
I installed 1.1.0 NuGet package for a 4.5 version .NET project

Can't get 
`using FastMember;`
to work

**Comment by mgravell** [comment]
could you try 1.3.0 instead?

**Comment by mgravell** [comment]
Onwards, the lowest level I'm currently supporting is .NETFramework 4.6.1; the main reason for this is that I **lack the capacity to test and support** anything lower, so it would be a false claim to make. If someone wants to build for down-level, they can do that from source relatively easily.
