### ISSUE TITLE
GetAttribute always returns null

### ISSUE THREAD

**Issue by danielcrenna** [mgravell/fast-member#55]
In COREFX, this line is never correct because the attribute type is searching itself for itself:

`return attributeType.GetTypeInfo().GetCustomAttribute(attributeType, inherit);`

It should probably be:

`return member.GetCustomAttribute(attributeType, inherit);`

**Comment by mgravell** [comment]
Well, derp. Noted, ta. Will fix.

**Comment by danielcrenna** [comment]
Closing because the rewrite removed the offending code.
