### ISSUE TITLE
Microsoft delisted System.Reflection.Emit.Lightweight for .NET Standard

### ISSUE THREAD

**Issue by danielcrenna** [mgravell/fast-member#57]
FYI: https://www.nuget.org/packages/System.Reflection.Emit.Lightweight

The ripple effect is that libraries should change to the NETCOREAPP TPM vs NETSTANDARD, which might have implications for wider use, though worth noting that this namespace doesn't actually have support on all NETSTANDARD implementations, it turns out.

Microsoft thread: https://github.com/dotnet/corefx/issues/29365

**Comment by mgravell** [comment]
Thanks, will look

**Comment by danielcrenna** [comment]
This can be closed. They brought it back.
