### ISSUE TITLE
1.4.0  .NET Standard dependencies

### ISSUE THREAD

**Issue by PhilPJL** [mgravell/fast-member#61]
If I want to update my .NET 4.7 project to use FastMemberSigned 1.4.0, from 1.3.0 I will need these packages as well:

![image](https://user-images.githubusercontent.com/271656/42966968-a748421c-8b96-11e8-8022-1a3cc63c76bc.png)

Is this really necessary?

**Comment by mgravell** [comment]
I will take another look at the packaging, but ultimately they are empty
stubs for you *anyway* - the actual code comes from .NET Framework. It is
one of those balancing acts about whether it is better to have one TFM but
extra stub dependencies, vs multiple TFMs and a more complex packaging
story, but fewer dependencies on some frameworks.

**Comment by mgravell** [comment]
1.4.1 should have zero dependencies:

![image](https://user-images.githubusercontent.com/17328/42970476-4cf5919c-8ba1-11e8-94d1-c5595f1aab26.png)

**Comment by guitarzan** [comment]
I'm unable to update from version 1.3.0 in my project which targets .NET Framework 4.5.2. 

"Could not install package 'FastMember 1.4.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Was this deliberate or can it be fixed?

Thanks.

**Comment by mgravell** [comment]
I'll need to find a moment to look at the targets
