### ISSUE TITLE
What license does fast-member fall under

### ISSUE THREAD

**Issue by SFoster84** [mgravell/fast-member#65]
Hello,

Thanks for providing the great library.  Can you specify a license for it?

Thanks!

**Comment by danielcrenna** [comment]
@SFoster84 It's an unconventional way to do it, and not explicit, but you can see that the Nuget package is licensed under Apache 2.0: https://github.com/mgravell/fast-member/blob/master/FastMember/FastMember.csproj

**Comment by SFoster84** [comment]
works for me, thanks!

**Comment by mgravell** [comment]
I need to make it more obvious, but Apache 2 (
https://github.com/mgravell/fast-member/blob/master/FastMember/FastMember.csproj
).

Frankly, most of my OSS libs are essentially licensed under the "go, have
fun, do things - whatever things, just don't sue me and don't claim you own
the tool" license, but I don't have a name for that :)

**Comment by SFoster84** [comment]
:-) Cool, yeah, it's kind of a hassle to have to select/specify a license when you just want to provide some nice functionality for other developers; a nice formal one like MIT, Apache 2, etc are easier to bring to the company lawyer though ;-)

Maybe github could specify a default license you opt out of during the project creation, though I guess it's the same issue of them not wanting to take the liability of selecting for you.

**Comment by fuzzzerd** [comment]
Perhaps create a LICENSE file in the repository root to match contents the link (http://www.apache.org/licenses/LICENSE-2.0) in project file? That way it will also show up in the github interface.

**Comment by mgravell** [comment]
license added to project root, thanks
