### ISSUE TITLE
net core 2.1.1 Install - yellow triangle in dependencies

### ISSUE THREAD

**Issue by OrangeGoblin1973** [mgravell/fast-member#69]
I am trying to use the package, and have tried all of them which are available on NuGet (including netcore version), but I cannot get the package to appear as a dependency. Is there a guide or something similar to advise the install. TIA

**Comment by danielcrenna** [comment]
@OrangeGoblin1973 There isn't a netcore version, there is a `netstandard2.0` version, which should work on any `netcoreapp2.*` version.

![image](https://user-images.githubusercontent.com/129610/54102848-659b0f80-43a0-11e9-996b-2283371fcf8d.png)

I couldn't reproduce this. What does it say in your `.csproj`?

**Comment by mgravell** [comment]
there's also now a netcoreapp2.0 build (in 1.5.0) with zero dependencies
