### ISSUE TITLE
C# Named Tuples

### ISSUE THREAD

**Issue by NickLarsen** [mgravell/fast-member#72]
```
IEnumerable<(int Id, byte[] Values)> data = new[]
{
	(Id: 1, Values: new byte[1]),
	(Id: 2, Values: new byte[2]),
};
var table = new DataTable();
using (var reader = ObjectReader.Create(data, "Id", "Values"))
{
	table.Load(reader);
}

// throws ArgumentOutOfRangeException: 
// "Specified argument was out of the range of valid values.Parameter name: name"
```

Was trying to do some quick and dirty data transfer and ran into this.  I fixed it by writing a wrapper class but it would have been nice not to have to do that.  It looks like the underlying implementation it's picking up is that of a plain old tuple and it finds properties for `Item1` and `Item2` by default if you don't specify the names when creating the `ObjectReader`.

**Comment by mgravell** [comment]
Cannot be solved. Value-tuples only expose names *outward*, never inward.
So: callers can see the names, but callees cannot. Library code is always a
callee, so never gets names from value-tuples.

There is no current API or language feature that I can use to avoid this.
