### ISSUE TITLE
Which version to use for .NET Core development

### ISSUE THREAD

**Issue by sheelgohe** [mgravell/fast-member#74]
Hi Marc,
You have an amazing library. I just want to check which version of FastMember to use for .NET core 2.1 development project. We are successfully able to run both FastMember 1.3 and FastMember .NET Core version 1.1.0. Which library is the better one in terms of future support and bug fixes.

Appreciate your advise.

Thanks,
Sheel

**Comment by mgravell** [comment]
Nuget's current version is [1.4.1](https://www.nuget.org/packages/FastMember/1.4.1), which supports .NET Standard 2.0, so I'd say: use that. I'm not sure why you'd use 1.3 or 1.1.0 at this point, and if there is a reason: please let me know so I can compensate.

**Comment by sheelgohe** [comment]
Hi Marc,
Thanks for your response. We will switch to version 1.4.1.

Regards,
Sheel

**Comment by mgravell** [comment]
1.5 is en-route to nuget, and includes a .netcoreapp2.0 target with zero external dependencies
