### ISSUE TITLE
License has no copyright info

### ISSUE THREAD

**Issue by carlescs** [mgravell/fast-member#95]
The license file has no copyright info so we're having a hard time knowing how to correctly give proper attribution. Can it be added to it?

Thanks

**Comment by mgravell** [comment]
The copyright info could be more explicit, although I'm not sure the
license file is the right place - and it is in the csproj for the
packaging, but for reference, is is simply "© Marc Gravell, 2012-"

**Comment by carlescs** [comment]
There's an empty placeholder almost at the bottom of the license file. You might want to either fill it or remove it... 

Thanks for the info!

**Comment by mgravell** [comment]
Oops! you're right; fixed
